services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
      target: maintainer-node
    #ports: ['4211:4211']
    tty: true
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
      - ~/id_rsa:/root/.ssh/id_rsa
